- name: variables from args
  hosts: local
  connection: local
  tasks:
  - name: display variables
    ansible.builtin.debug:
      msg: "course name is {{ course }} , trainer name is {{ trainer }} and duration is {{ duration }}"