- name: conditions
  hosts: local
  connection: local
  vars:
    number: 5
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
    msg: "number {{ number }} is less than 10"
    when: number < 10
