- name: loops example
  hosts: local
  connection: local
  become: true
  tasks:
  - name: display names
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "nginx" , state: "absent" }
    - { name: "zip" , state: "latest" }
    - { name: "mysql" , state: "absent" }
     