- name: loops example
  hosts: local
  connection: local
  become: true
  tasks:
  - name: display names
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - zip
    - mysql
     